### PR TITLE
Add code coverage using Istanbul

### PR DESCRIPTION
**Pull request by silvestreh**
Running `npm test` will create a `coverage` directory with the report in it.

### CODE REVIEW

**Comment by silvestreh** [comment]
Trying to figure out why tests failed in Node 4.0.0 yet passed on 5.0.0 😕

**Comment by eventualbuddha** [comment]
Neat! Should we add `coverage/` to the `.gitignore` file?

**Comment by silvestreh** [comment]
@eventualbuddha Yes, sorry about that. It should be ignored now!

**Comment by eventualbuddha** [comment]
Sorry, one more thing I thought of: can you add information about the coverage tools to the Readme along with how to remove them if people don't want it? Thanks!

**Comment by silvestreh** [comment]
Just pushed the updated README file. Please double check it because English isn't my primary language 😄 .

**Comment by eventualbuddha** [comment]
Looks great. Thanks!

**Pull request merged**
